projects:
  app:
    schemaPath: server/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: database/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml